logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /opt/webapp/app_log_file.log
      record_log_file_path: true
  processors:
    parse_python_multiline:
      type: parse_multiline
      match_any:
      - type: language_exceptions
        language: python
    my-app-processor:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%d %H:%M:%S"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.levelname
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [parse_python_multiline, my-app-processor, move_severity]

